### PR TITLE
remove properties from measurement schema

### PR DESCRIPTION
**Pull request by vincenzodomina**
Discuss removal of the potentially unused properties:
- original_start_at
- deletion_reason
- deleted_at
- error
- location
- duration
- original_unit_id
- original_value
- client_id
- unit_id ??

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by mikepsinn** [comment]
I think they're useful but I guess not absolutely necessary so you can remove if you like.

**Comment by vincenzodomina** [comment]
Could these features be replaced with other mechanisms, for example "soft delete" and restoring original values through reprocessing of saved files, and translating string locations into long and latitude?

does this removal of these columns then improve the performance time of the queries?

**Comment by mikepsinn** [comment]
Yeah, that's fine. But I think you'd see the same performance improvements by simply excluding the columns from your query. 

I'd be most reluctant to remove the `deleted_at` column. You lose the option for undo or a trash can feature on the front end.   It's going to be a pain to delete and/ or retrieve specific measurements from text files.

**Comment by vincenzodomina** [comment]
Thanks Mike! 
Agree with the deleted property, that could be a very expected use case for manual entries. 

Wasn't aware of excluding columns is possible, what makes then the columnar database design more performant? That's seems similar. Or you mean you remove the files in the backend after fetching to reduce latency from http datasize?

**Comment by mikepsinn** [comment]
I'm thinking the files should rarely be interacted with. I'm saying if you just need the timestamp and value, you just
```
Select value, start_at where user_id=230 and variable_id=1398
```

This reduces the read time in the query achieving the same result as deleting columns. 

@vincenzodomina

**Pull request merged**
