### PR TITLE
Simplified variable category table and content

### PR DESCRIPTION
**Pull request by vincenzodomina**
This would be my proposal draft for a simplified category table

- Merged "Movies", "Electronics", "Software" into digital services
- Added functional, laboratory, observations
- Observations would include emotions, replace?
- Added descriptions for displaying purpose

From the removed properties, am I missing some important features where to to be used that info?

Categories I did not include so far are genetics and imaging, to be discussed.

Please let's have a further discussion. 

<sub> Mention [stepsize] in a comment if you'd like to report some technical debt. See examples [here](https://app.stepsize.com/api/demo-pr-redirect).</sub>

### CODE REVIEW

**Comment by vincenzodomina** [comment]
Proposal:
Lets replace treatments in favor of medication, supplements, therapies
Lets use emotions or observations (for emotions and others like Sneezings/day)?
...to avoid overlaps and be consistent on the more precise subcategories (e.g. like sleep, cognitive,.. instead of just biomarkers)

**Comment by mikepsinn** [comment]
Medications and supplements are therapies. So it's unclear what category to use.

**Comment by vincenzodomina** [comment]
> 

Ok, I thought of therapies in terms of doing something instead of taking something orally e.g. stem cell therapy, red light therapy, sauna, massage

Is there a better word for this then?

**Comment by mikepsinn** [comment]
We're going to have to put the category id's in the measurements table to enable indexes and fast queries. The latency and DB size is higher if we have to return more data, i.e. long strings instead of short numbers.

**Comment by mikepsinn** [comment]
Sneezes are symptoms,  right?

**Comment by vincenzodomina** [comment]
> Sneezes are symptoms, right?

Correct, but what about the flow state, thats not an emotion right?

**Comment by vincenzodomina** [comment]
In the descriptions I tried to draw the lines, there is many overlaps, e.g.anxiety is a emotion as well as a symptom

**Comment by vincenzodomina** [comment]
Merging for now to work off from this point

**Comment by vincenzodomina** [comment]
Notes:
- TBD another word for therapies (regarding non orally taken stuff like red-light-therapy)
- TBD remove treatments in favor of medication, supplements and therapies?
- TBD best name for physical measurements
- TBD Health goals specifically or goals in general and health goals separate table?
- TBD another word for laboratory to include also home tests e.g. Tissue Analysis
- TBD cognition part of functional tests?

**Pull request merged**
